

ARDCONST:= src/controller/constants.hpp
PYCONST:= src/constants.py
CONSTANTS:= src/constants.in

SHELL:=/bin/bash

srcdir:=src/

source:=$(wildcard src/*)
source+=$(wildcard *.md)

pdfman:=refman.pdf

.PHONEY: all documentation super_clean constants

all: constants documentation


################################################################################
#                                CONSTANTS HEADERS
################################################################################


constants: $(PYCONST) $(ARDCONST)

boilerplate:="This file has been autogenerated, CHANGES MADE HERE WILL NOT PERSIST"

$(PYCONST) $(ARDCONST): src/constants.in Makefile
	echo -en "/**\t@file $(ARDCONST)\n " > $(ARDCONST)
	echo -e "##\t@file $(PYCONST)"  > $(PYCONST)
	HEADER=true                                        ;\
	cat $(CONSTANTS) | while read -r line; do           \
		if $$HEADER; then                               \
			if test "$$line" == "%%"; then              \
				echo -e "*\t$(boilerplate)\n */\n\n" >> $(ARDCONST) ;\
				echo -e "#\t$(boilerplate)\n"        >> $(PYCONST)  ;\
				HEADER=false                           ;\
			else                                        \
				echo -ne "*\t$$line\n " >> $(ARDCONST) ;\
				echo -e "#\t$$line"  >> $(PYCONST)     ;\
			fi                                          \
		elif test "$$line" != ""; then                  \
			words=($$line)                             ;\
			echo "#define $${words[0]} $${words[1]} ///< $${words[@]:2:100}" >> $(ARDCONST) ;\
			echo -e "## $${words[@]:2:100}\n$${words[0]} = $${words[1]}" >> $(PYCONST) ;\
			#echo "$${words[0]} = $${words[1]} ###< $${words[@]:2:100}" >> $(PYCONST) ;\
		fi \
	done


################################################################################
#                                DOCUMENTATION
################################################################################

documentation: docs latex $(pdfman)

$(pdfman): latex
	$(MAKE) -C latex all
	cp latex/refman.pdf ./


docs latex: doxygen.cfg $(source) constants
	rm -fr docs latex $(pdfman)
	doxygen doxygen.cfg


################################################################################
#                                    CLEAN
################################################################################


super_clean:
	rm -fr docs latex $(pdfman) $(ARDCONST) $(PYCONST)


