/**	@file src/controller/constants.hpp
 *	Constants shared across the whole system.
 *	Includes constants used by both the arduino sketch and the the python script.
 *	The format of `constants.in` is three whitespace sparated columns:
 *	
 *	[NAME] [value] [comments]
 *	
 *	Any changes must be made in `constants.in` and followed by running:
 *	
 *	`make constants`
 *	
 *	--ABD
 *	
 *	@copyright Copyright &copy; 2019 by the authors. All rights reserved.
 *	
 *	This file has been autogenerated, CHANGES MADE HERE WILL NOT PERSIST
 */


#define ARM_AZIMUTH_MIN 0 ///< 
#define ARM_AZIMUTH_MAX 0 ///< 
#define ARM_RANGE_MIN 0 ///< 
#define ARM_RANGE_MAX 0 ///< 
#define ARM_ORIENT_MIN 0 ///< 
#define ARM_ORIENT_MAX 0 ///< 
#define PICKUP_X_MIN 0 ///< 
#define PICKUP_X_MAX 0 ///< 
#define PICKUP_Y_MIN 0 ///< 
#define PICKUP_Y_MAX 0 ///< 
#define ARDUINO_NULL 0x00 ///< A place holder for troubleshooting etc.
#define ARDUINO_STATUS_ACK 0x01 ///< If the arduino needs to acknowledge something
#define ARDUINO_STATUS_READY 0x02 ///< If the arduino needs to indicate it is ready
#define ARDUINO_STATUS_PICK_FAIL 0x03 ///< Report that the pick failed
#define ARDUINO_STATUS_PICK_SUCCESS 0x04 ///< Report that the pick succeded
#define ARDUINO_STATUS_ARM_FAULT 0x05 ///< Report a general arm failure
#define ARDUINO_STATUS_OBSTACLE 0x06 ///< Report an obstacle detected
#define ARDUINO_ROTATE 0x10 ///< command the arduino to rotate the robot. This byte is followed by a signed byte indicating magnitude and direction
#define ARDUINO_MOVE 0x11 ///< command the arduino to advance the robot. This byte is followed by a signed byte indicating magnitude and direction
#define ARDUINO_LINE_FOLLOW 0x12 ///< command the arduino to follow the line
#define ARDUINO_ARM_PARK 0x20 ///< call the park action sequence
#define ARDUINO_ARM_DISPOSE 0x21 ///< call the dispose action sequence
#define ARDUINO_ARM_PICKUP 0x22 ///< attempt a pick, followed by three bytes: azimuth, range, and orientation
#define PORT_MOTOR_FWD None ///< 
#define PORT_MOTOR_AFT None ///< 
#define STBD_MOTOR_FWD None ///< 
#define STBD_MOTOR_AFT None ///< 
#define PORT_LINE_SENSE None ///< 
#define STBD_LINE_SENSE None ///< 
#define PORT_FWD_OBSTACLE None ///< 
#define PORT_AFT_OBSTACLE None ///< 
#define STBD_FWD_OBSTACLE None ///< 
#define STBD_AFT_OBSTACLE None ///< 
#define ARM_CONTROL None ///< 
